image: nikolaik/python-nodejs
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run build
          - pip install awscli --upgrade --ignore-installed six
          - aws s3 sync ./build s3://www.onepos.lk
          - aws s3 cp --cache-control max-age=0 ./build/service-worker.js s3://www.onepos.lk/
